* ybapp

A little application to parse an xlsx file and download any linked
files therein.

** Development

To build ~ybapp~:

*** using ~stack~ (easy)

1. [[https://github.com/commercialhaskell/stack#how-to-install][Install stack]]
2. Clone the respository and build with stack:
   #+BEGIN_SRC sh
     git clone https://github.com/mjhoy/ybapp.git
     cd ybapp
     stack setup
     stack build
     stack exec ybapp
   #+END_SRC

*** using ~nix~

(assuming you've got a working nix install), all you should need to do
is run ~nix-shell~ in the repository to set up a build environment,
and then the normal cabal commands:

#+BEGIN_SRC sh
  cd ybapp
  nix-shell
  cabal configure
  cabal build
  # should produce executable in dist/
#+END_SRC

** Instructions
:PROPERTIES:
:EXPORT_OPTIONS: toc:nil
:END:

Double-click =ybapp.command= to open the YellowBarn application
downloader.

You will be asked to select an excel file, and a folder for
download. Simply drag these onto the terminal window that appears and
then press RETURN to select them.

If you do not select a download folder and simply press RETURN, a
folder will be created on your desktop called "ybapp_downloads" where
downloaded files will be put.

If at any time you need to stop or quit the program, press
Control-c. You may then quit the Terminal application.
